site_name: ZT2 API Documentation
pages:
    - Home: index.md
    - behaviors: behaviors.md
    - about: about.md
theme: readthedocs

markdown_extensions:
    - toc:
        permalink: ïƒ
    # - admonition
    # - def_list
    # - mdx_gh_links:
        # user: mkdocs
# repo: mkdocs